// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddFeed(arg1:string):Promise<void>;

export function GetFeeds():Promise<Array<app.Feed>>;

export function GetItems(arg1:string):Promise<Array<app.Item>>;

export function RefreshFeed(arg1:string):Promise<void>;
