// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddFeed(arg1:string):Promise<app.Feed>;

export function Feeds():Promise<Array<app.Feed>>;
