// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {feed} from '../models';

export function ParseURL(arg1:string):Promise<feed.Feed>;
