// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseURL(arg1) {
  return window['go']['feed']['Parser']['ParseURL'](arg1);
}
